### ISSUE TITLE
Error When Running Build.sh

### ISSUE THREAD

**Issue by riveracarvelli** [svr4/winter#2]
When running the build.sh file to install the program I get the following error:

> ./build.sh 
> ../../.go/src/easyterm/easyterm.go:6:2: cannot find package "github.com/pkg/term/termios" in any of:
> 	/home/riveracarvelli/.go/src/vendor/github.com/pkg/term/termios (vendor tree)
> 	/home/riveracarvelli/.go/src/github.com/pkg/term/termios (from $GOROOT)
> 	/home/riveracarvelli/go/src/github.com/pkg/term/termios (from $GOPATH)
> ../../.go/src/easyterm/easyterm.go:5:2: cannot find package "golang.org/x/sys/unix" in any of:
> 	/home/riveracarvelli/.go/src/vendor/golang.org/x/sys/unix (vendor tree)
> 	/home/riveracarvelli/.go/src/golang.org/x/sys/unix (from $GOROOT)
> 	/home/riveracarvelli/go/src/golang.org/x/sys/unix (from $GOPATH)
> 

The easyterm lib is looking for termios in an invalid http address because _**"github.com/pkg/term/termios"**_ points to an invalid page. Seems like the correct page is _**"github.com/pkg/term/tree/master/termios"**_

**Comment by svr4** [comment]
Hey riveracarvelli,

The file "build.sh" is actually something I used in development to speed up building the source and to enable step by step debugging in VS Code. You should try running a `go get` before running build.sh again. I pushed a fix removing the "github.com/pkg/term/termios" dependency so you can try again with that commit. It's tagged as v0.2.23-beta.

Thanks for the feedback, keep it coming.
